### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#33]
I can understand that you would like to keep permissions to a minimum but this causes a couple of problems. Namely:

1. Initial use has a permission request message containing a difficult-to-understand sentence about having to switch a couple of different things on or off in settings. It's not the most positive of starts and gets quite confusing if the user fiddles with notifications settings.
2. Custom notification sounds can be chosen from storage but can't be used because storage permission doesn't exist.

 In the interest of making the life of the average user a bit easier, I propose they should either be forced to accept the permissions or that alternatives should be reduced in number.

**Comment by udamken** [comment]
1. I want to make sure users are using (or are at least aware of) the notification icon. Otherwise there would be a lot more "why doesn't my bell sound, why is it muted, how can I see it's muted?" questions. Users can avoid the difficult-to-understand explanation by granting the permission directly ;-) ... do you have an idea for an easier-to-understand explanation? Then please file a new issue with the current explanation and your suggestion.
2. See issue #12. You should only be able to select notification sounds which do not need an additional permission, maybe this is another device dependend issue.

With Android 6.0 users aren't be forced to accept permissions. They even can withdraw permissions later on. That's a fine thing from the users point of view - I myself appreciate that. But it's a lot more difficult to implement and test. See https://developer.android.com/training/articles/user-data-permissions.html and https://developer.android.com/training/permissions/requesting.html.

**Comment by dalb8** [comment]
In that case, perhaps the notification should be forced or at least allow the text to be customisable. Sure, some people will block it but not too many.

 OK I'll have a think about improving the explanation but you know what politicians say: when you're explaining you're losing ;-)
