### ISSUE TITLE
Quick (un)mute

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#50]
In most cases one would like to mute mindbell for an hour, e.g. when one has a nap or when watches a video.

 At the moment there are quite a few presses to mute and unmute mindbell. 

I propose having the notification mute mindbell for just an hour, with a setting to change this.

**Comment by dalb8** [comment]
It probably makes more sense to use do not disturb mode when taking a nap but then this isn't available on Android 4.

**Comment by dalb8** [comment]
If not, the counter can be set to 1 instead of 0 when opening the mute dialogue

**Comment by udamken** [comment]
I've learned that there are a million ways to achieve something like this. "Mute for ..." is designed for users that do not want to use do-not-disturb (in 3 flavors), nor flight mode, nor volume settings, nor vibration mode ... but only want to mute the bell because it might be embarrassing in a meeting whereas it's accepted to get an urgent phone call.

Changing the default to 1 h could be an option. But default should be off if bell is already muted.

**Comment by udamken** [comment]
Android Oreo no longer allows apps to receive all implicit broadcast that MindBell needs to update the status notification. Therefore some of this functionality will go to Quick Settings. If already working on this there will be a quick mute/unmute for this, I think.

**Comment by udamken** [comment]
Mute dialog now defaults to off if MindBell is muted or, otherwise, to the hours chosen the last time (or 2 if it's the first time). Quick Settings tile now opens mute dialog if phone is unlocked. If phone is locked Quick Settings tiles unmutes if muted or, otherwise, mutes for the hours chosen the last time (or 2 if it's the first time).
