### ISSUE TITLE
New intro text

### ISSUE THREAD

**Issue by dalb8** [udamken/mindbell#57]
I thought I could improve the introduction text:

MindBell

When the switch at the top is on MindBell will sound throughout the day, encouraging you to pause and become mindful of what you are doing and in what state of mind you are in.

MindBell is muted while the phone itself is muted and while taking phone calls. It can also be muted manually for an hour or two. For information on how to regulate MindBell please refer to the online Help.

Next to the switch is a button to enable meditation mode during which the bell only rings to signal the start and end of meditation.

(I don't see any need for "tap to ring")

**Comment by udamken** [comment]
Great idea, makes it more obvious how to use MindBell. I've replaced "tap to ring" by a "play" button because it might be useful to ring the bell once - and if only to test the sound. But "tap to ring" is no longer needed to give the hint how to activate the bell.

To be released in version 3.2.3

**Comment by udamken** [comment]
"Tap to ring" is far away from being obsolete. After replacing it by a "play" button several users requested that they would like to tap the bell again. So I reintroduced that feature. I also reintroduced to tap the time slice while meditating because ringing the bell during meditation might be useful if you are guiding a meditation and have no real bell with you.
